rules-config:
  no-recent-package-release:
    warn-at-months: 12
    fail-at-months: 36
  no-recent-commit:
    warn-at-months: 12
    fail-at-months: 36
  few-yearly-commits:
    warn-at-count: 5
    # few-yearly-commits only warns by default, unless fail-at-count is set
    # fail-at-count: 6
ignore-failures:
  - langs
  - cross-env
  - classnames
  - @zeit/next-sass
  - @zeit/next-css
